name: "Assets sync"
description: "Deploy asset files to multiple repositories."
inputs:
  repos:
    description: "Space separated list of target repository slugs."
    required: true
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  git_user:
    description: "User name of commit author."
    required: true
  git_email:
    description: "E-mail address of commit author."
    required: true
  commit_message:
    description: "Commit message of generated commits. Defaults to 'Update assets to %v'. ('%v': version tag string)"
  dryrun:
    description: "Set true to run the job without pushing."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "refresh-ccw"
  color: "yellow"
