name: "Assets sync"
description: "Deploy asset files to multiple repositories."
inputs:
  repos:
    description: "Space separated list of target repository slugs."
    required: true
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  git_user:
    description: "User name of commit author."
    required: true
  git_email:
    description: "E-mail address of commit author."
    required: true
  commit_message:
    description: "Commit message of generated commits. Defaults to 'Update assets to %v'. ('%v': version tag string)"
  branch:
    description: "Branch name to which the changes are committed. Defaults to 'sync-assets-%v'. ('%v': version tag string)"
  root_dir:
    description: "Root directory of the assets for this job. Defaults to 'root'."
  rm:
    description: "Files to be removed."
  dryrun:
    description: "Set true to run the job without pushing."
  exclude_paths:
    description: "Space separated list of excluded path globs."
  force_push:
    description: "Set true to force push sync branch."
  push_interval:
    description: "Push interval to avoid abuse detection."
  script:
    description: "Bash script to run in target repo before committing. ASSETS_DIR env var points to the source assets directory."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "refresh-ccw"
  color: "yellow"
